import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/**
 * Export the current page content as a branded PDF report.
 * Captures the <main> content area, adds a header with branding, and downloads.
 */
export async function exportPagePdf(pageTitle: string) {
  const main = document.querySelector('main');
  if (!main) return;

  // Temporarily hide the top bar (date picker) for cleaner export
  const topBar = main.querySelector('.flex.justify-end.mb-4') as HTMLElement | null;
  if (topBar) topBar.style.display = 'none';

  const canvas = await html2canvas(main as HTMLElement, {
    backgroundColor: '#000000',
    scale: 2,
    useCORS: true,
    logging: false,
    windowWidth: 1280,
  });

  // Restore top bar
  if (topBar) topBar.style.display = '';

  const imgWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  const pdf = new jsPDF('p', 'mm', 'a4');

  // Header bar
  pdf.setFillColor(10, 10, 10);
  pdf.rect(0, 0, 210, 16, 'F');
  pdf.setFontSize(11);
  pdf.setTextColor(200, 168, 78); // gold
  pdf.text('CAA ANALYTICS', 10, 10);
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text(`${pageTitle}  |  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 210 - 10, 10, { align: 'right' });

  // Content - paginate if needed
  const contentStartY = 18;
  const availableHeight = pageHeight - contentStartY - 8; // 8mm bottom margin
  const scaledPageHeight = (availableHeight * canvas.width) / imgWidth;

  let position = 0;
  let page = 0;

  while (position < canvas.height) {
    if (page > 0) {
      pdf.addPage();
      // Repeat header on subsequent pages
      pdf.setFillColor(10, 10, 10);
      pdf.rect(0, 0, 210, 16, 'F');
      pdf.setFontSize(11);
      pdf.setTextColor(200, 168, 78);
      pdf.text('CAA ANALYTICS', 10, 10);
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text(`${pageTitle}  |  Page ${page + 1}`, 210 - 10, 10, { align: 'right' });
    }

    // Crop section of the canvas for this page
    const sliceHeight = Math.min(scaledPageHeight, canvas.height - position);
    const pageCanvas = document.createElement('canvas');
    pageCanvas.width = canvas.width;
    pageCanvas.height = sliceHeight;
    const ctx = pageCanvas.getContext('2d');
    if (ctx) {
      ctx.drawImage(canvas, 0, position, canvas.width, sliceHeight, 0, 0, canvas.width, sliceHeight);
    }

    const pageImg = pageCanvas.toDataURL('image/png');
    const sliceImgHeight = (sliceHeight * imgWidth) / canvas.width;
    pdf.addImage(pageImg, 'PNG', 0, contentStartY, imgWidth, sliceImgHeight);

    position += scaledPageHeight;
    page++;
  }

  // Footer on last page
  pdf.setFontSize(7);
  pdf.setTextColor(74, 74, 74);
  pdf.text('Generated by Miraki AI - CAA Analytics Platform', 105, pageHeight - 5, { align: 'center' });

  pdf.save(`${pageTitle.replace(/\s+/g, '_').toLowerCase()}_report.pdf`);
}
